/**
 * Centralized Organization Permission Catalog for Nexus
 */
const SYSTEM_PERMISSIONS = [
  // Employees Module
  {
    key: 'employees.read',
    name: 'View Employees',
    description: 'Allows viewing employee directory and profiles',
    module: 'employees',
    action: 'read',
  },
  {
    key: 'employees.create',
    name: 'Create Employees',
    description: 'Allows adding new employees to the organization',
    module: 'employees',
    action: 'create',
  },
  {
    key: 'employees.update',
    name: 'Update Employees',
    description: 'Allows modifying existing employee records',
    module: 'employees',
    action: 'update',
  },
  {
    key: 'employees.delete',
    name: 'Delete Employees',
    description: 'Allows removing employees from the organization',
    module: 'employees',
    action: 'delete',
  },

  // Departments Module
  {
    key: 'departments.read',
    name: 'View Departments',
    description: 'Allows viewing department list and organizational structure',
    module: 'departments',
    action: 'read',
  },
  {
    key: 'departments.create',
    name: 'Create Departments',
    description: 'Allows creating new departments',
    module: 'departments',
    action: 'create',
  },
  {
    key: 'departments.update',
    name: 'Update Departments',
    description: 'Allows editing department configurations',
    module: 'departments',
    action: 'update',
  },
  {
    key: 'departments.delete',
    name: 'Delete Departments',
    description: 'Allows deleting departments',
    module: 'departments',
    action: 'delete',
  },

  // Workflows Module
  {
    key: 'workflows.read',
    name: 'View Workflows',
    description: 'Allows viewing business workflow pipelines',
    module: 'workflows',
    action: 'read',
  },
  {
    key: 'workflows.create',
    name: 'Create Workflows',
    description: 'Allows authoring automated workflow processes',
    module: 'workflows',
    action: 'create',
  },
  {
    key: 'workflows.update',
    name: 'Update Workflows',
    description: 'Allows updating workflow diagrams and states',
    module: 'workflows',
    action: 'update',
  },
  {
    key: 'workflows.delete',
    name: 'Delete Workflows',
    description: 'Allows deleting workflow processes',
    module: 'workflows',
    action: 'delete',
  },

  // Requests Module
  {
    key: 'requests.read',
    name: 'View Requests',
    description: 'Allows viewing internal service requests and tickets',
    module: 'requests',
    action: 'read',
  },
  {
    key: 'requests.create',
    name: 'Create Requests',
    description: 'Allows raising new requests',
    module: 'requests',
    action: 'create',
  },
  {
    key: 'requests.update',
    name: 'Update Requests',
    description: 'Allows editing open request details',
    module: 'requests',
    action: 'update',
  },
  {
    key: 'requests.cancel',
    name: 'Cancel Requests',
    description: 'Allows cancelling raised requests',
    module: 'requests',
    action: 'cancel',
  },

  // Approvals Module
  {
    key: 'approvals.read',
    name: 'View Approvals',
    description: 'Allows viewing pending and completed approval queues',
    module: 'approvals',
    action: 'read',
  },
  {
    key: 'approvals.approve',
    name: 'Approve Items',
    description: 'Allows approving pending operational requests',
    module: 'approvals',
    action: 'approve',
  },
  {
    key: 'approvals.reject',
    name: 'Reject Items',
    description: 'Allows rejecting operational requests',
    module: 'approvals',
    action: 'reject',
  },

  // Forms Module
  {
    key: 'forms.read',
    name: 'View Forms',
    description: 'Allows viewing custom forms and submissions',
    module: 'forms',
    action: 'read',
  },
  {
    key: 'forms.create',
    name: 'Create Forms',
    description: 'Allows designing new dynamic form templates',
    module: 'forms',
    action: 'create',
  },
  {
    key: 'forms.update',
    name: 'Update Forms',
    description: 'Allows modifying form schemas and validations',
    module: 'forms',
    action: 'update',
  },
  {
    key: 'forms.delete',
    name: 'Delete Forms',
    description: 'Allows deleting form templates',
    module: 'forms',
    action: 'delete',
  },

  // Support Module
  {
    key: 'support.read',
    name: 'View Support Tickets',
    description: 'Allows viewing helpdesk and support discussions',
    module: 'support',
    action: 'read',
  },
  {
    key: 'support.create',
    name: 'Create Support Tickets',
    description: 'Allows opening new support requests',
    module: 'support',
    action: 'create',
  },
  {
    key: 'support.update',
    name: 'Update Support Tickets',
    description: 'Allows replying to and updating support threads',
    module: 'support',
    action: 'update',
  },

  // Roles & Permissions Module
  {
    key: 'roles.read',
    name: 'View Roles',
    description: 'Allows viewing organization roles and permissions',
    module: 'roles',
    action: 'read',
  },
  {
    key: 'roles.create',
    name: 'Create Roles',
    description: 'Allows creating custom organizational roles',
    module: 'roles',
    action: 'create',
  },
  {
    key: 'roles.update',
    name: 'Update Roles',
    description: 'Allows modifying role permissions and assigning member roles',
    module: 'roles',
    action: 'update',
  },
  {
    key: 'roles.delete',
    name: 'Delete Roles',
    description: 'Allows deleting custom roles',
    module: 'roles',
    action: 'delete',
  },

  // Settings Module
  {
    key: 'settings.read',
    name: 'View Organization Settings',
    description: 'Allows viewing organization configuration',
    module: 'settings',
    action: 'read',
  },
  {
    key: 'settings.update',
    name: 'Update Organization Settings',
    description: 'Allows modifying organization settings and domain restrictions',
    module: 'settings',
    action: 'update',
  },
  // Tasks & Delegation Module
  {
    key: 'tasks.read',
    name: 'View Tasks',
    description: 'Allows viewing assigned, delegated, and organization tasks',
    module: 'tasks',
    action: 'read',
  },
  {
    key: 'tasks.create',
    name: 'Create & Assign Tasks',
    description: 'Allows assigning tasks to organization employees',
    module: 'tasks',
    action: 'create',
  },
  {
    key: 'tasks.update',
    name: 'Update Tasks',
    description: 'Allows editing task metadata and status',
    module: 'tasks',
    action: 'update',
  },
  {
    key: 'tasks.complete',
    name: 'Complete Tasks',
    description: 'Allows marking owned tasks as completed',
    module: 'tasks',
    action: 'complete',
  },
  {
    key: 'tasks.delegate',
    name: 'Delegate Tasks',
    description: 'Allows delegating owned tasks to eligible team members',
    module: 'tasks',
    action: 'delegate',
  },
  {
    key: 'tasks.cancel',
    name: 'Cancel Tasks',
    description: 'Allows cancelling assigned or authored tasks',
    module: 'tasks',
    action: 'cancel',
  },
];

const VALID_PERMISSION_KEYS = new Set(SYSTEM_PERMISSIONS.map((p) => p.key));

// Default role permission matrices
const DEFAULT_ROLE_PERMISSIONS = {
  owner: ['*'], // Implicitly has everything
  admin: [
    'employees.read',
    'employees.create',
    'employees.update',
    'employees.delete',
    'departments.read',
    'departments.create',
    'departments.update',
    'departments.delete',
    'workflows.read',
    'workflows.create',
    'workflows.update',
    'workflows.delete',
    'requests.read',
    'requests.create',
    'requests.update',
    'requests.cancel',
    'approvals.read',
    'approvals.approve',
    'approvals.reject',
    'tasks.read',
    'tasks.create',
    'tasks.update',
    'tasks.complete',
    'tasks.delegate',
    'tasks.cancel',
    'forms.read',
    'forms.create',
    'forms.update',
    'forms.delete',
    'support.read',
    'support.create',
    'support.update',
    'roles.read',
    'roles.create',
    'roles.update',
    'settings.read',
    'settings.update',
  ],
  manager: [
    'employees.read',
    'employees.create',
    'employees.update',
    'departments.read',
    'workflows.read',
    'workflows.create',
    'workflows.update',
    'requests.read',
    'requests.create',
    'requests.update',
    'requests.cancel',
    'approvals.read',
    'approvals.approve',
    'approvals.reject',
    'tasks.read',
    'tasks.create',
    'tasks.update',
    'tasks.complete',
    'tasks.delegate',
    'tasks.cancel',
    'forms.read',
    'support.read',
    'support.create',
    'support.update',
  ],
  approver: [
    'employees.read',
    'departments.read',
    'workflows.read',
    'requests.read',
    'requests.create',
    'requests.cancel',
    'approvals.read',
    'approvals.approve',
    'approvals.reject',
    'tasks.read',
    'tasks.create',
    'tasks.complete',
    'tasks.delegate',
    'forms.read',
    'support.read',
    'support.create',
  ],
  member: [
    'employees.read',
    'departments.read',
    'workflows.read',
    'requests.read',
    'requests.create',
    'requests.cancel',
    'tasks.read',
    'tasks.create',
    'tasks.complete',
    'tasks.delegate',
    'forms.read',
    'support.read',
    'support.create',
  ],
};

module.exports = {
  SYSTEM_PERMISSIONS,
  VALID_PERMISSION_KEYS,
  DEFAULT_ROLE_PERMISSIONS,
};
